### PR TITLE
Header color

### PR DESCRIPTION
**Pull request by Vickenconcept**

### CODE REVIEW

**Comment by Succynice** [comment]
@TRIPLE-ADE @Chiemella @StanleyAnyas any of you can jump into this PR as well

best regards

**Review by Succynice — COMMENTED** [review]
@Vickenconcept sir I can't seem to find the changes you made

see below image for your reference
image

**Comment by Vickenconcept** [comment]
alright , just got issues then , so i had to push it, 
i have made the changes now

**Comment by Succynice** [comment]
Seen boss

**Review by Succynice — APPROVED** [review]
Great

**Pull request merged**
