### PR TITLE
Add workflow badges to README

### PR DESCRIPTION
**Pull request by Succynice**
still testing

### CODE REVIEW

**Comment by Succynice** [comment]
check review

**Review by Succynice — COMMENTED** [review]
all clear

**Review by Succynice — COMMENTED** [review]
@TRIPLE-ADE @Chiemella @Vickenconcept

any of you that sees this PR first can go ahead and review it

**Comment by Chiemella** [comment]
Re: @Succynice 
Seen boss, let's see how it goes sir. I think @TRIPLE-ADE @Vickenconcept @StanleyAnyas can also comment as well.

**Comment by Vickenconcept** [comment]
sees boss

**Comment by TRIPLE-ADE** [comment]
Seen bosses

**Comment by Succynice** [comment]
Alright team, 

can someone help in approving and merging the PR to the main branch

**Comment by StanleyAnyas** [comment]
Seen

**Pull request merged**
